=== Prajwalprasanna/DemoRepo/EmployeeDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/EmployeeDetails"
	xmlns:tns="http://www.example.org/EmployeeDetails"
	elementFormDefault="qualified">
	<element name="root">
		<complexType>
			<sequence>
				<element name="iSteer" minOccurs="5" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="empid">
								<simpleType>
									<restriction base="string">
										<minLength value="0"></minLength>
										<maxLength value="4"></maxLength>
									</restriction>
								</simpleType>
							</element>
							<element name="ename" type="string"></element>
							<element name="deptno" type="int"></element>
							<element name="sal" type="double"></element>
							<element name="job" type="string"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Prajwalprasanna/DemoRepo/EmployeeDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/EmployeeDetails" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/EmployeeDetails EmployeeDetails.xsd ">
  <tns:iSteer>
    <tns:empid>1234</tns:empid>
    <tns:ename>Sanjay</tns:ename>
    <tns:deptno>10</tns:deptno>
    <tns:sal>25000.0</tns:sal>
    <tns:job>thingsteer</tns:job>
  </tns:iSteer>
  <tns:iSteer>
    <tns:empid>1235</tns:empid>
    <tns:ename>tns:ename</tns:ename>
    <tns:deptno>0</tns:deptno>
    <tns:sal>0.0</tns:sal>
    <tns:job>tns:job</tns:job>
  </tns:iSteer>
  <tns:iSteer>
    <tns:empid>1236</tns:empid>
    <tns:ename>tns:ename</tns:ename>
    <tns:deptno>0</tns:deptno>
    <tns:sal>0.0</tns:sal>
    <tns:job>tns:job</tns:job>
  </tns:iSteer>
  <tns:iSteer>
    <tns:empid>1237</tns:empid>
    <tns:ename>tns:ename</tns:ename>
    <tns:deptno>0</tns:deptno>
    <tns:sal>0.0</tns:sal>
    <tns:job>tns:job</tns:job>
  </tns:iSteer>
  <tns:iSteer>
    <tns:empid>1238</tns:empid>
    <tns:ename>tns:ename</tns:ename>
    <tns:deptno>0</tns:deptno>
    <tns:sal>0.0</tns:sal>
    <tns:job>tns:job</tns:job>
  </tns:iSteer>
</tns:root>
