=== Prajwalprasanna/DemoRepo/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/student"
	xmlns:tns="http://www.example.org/student"
	elementFormDefault="qualified">
	<element name="root">
		<complexType>
			<sequence>
				<element name="student" minOccurs="5" maxOccurs="unbounded">
					<complexType>
						<sequence>

							<element name="stuID" type="int" />
							<element name="stuName" type="string" />
							<element name="stuAge" type="int" />

						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Prajwalprasanna/DemoRepo/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/student student.xsd ">
  <tns:student>
    <tns:stuID>123</tns:stuID>
    <tns:stuName>tns:Prajwal</tns:stuName>
    <tns:stuAge>22</tns:stuAge>
  </tns:student>
  <tns:student>
    <tns:stuID>124</tns:stuID>
    <tns:stuName>tns:Sanjay</tns:stuName>
    <tns:stuAge>22</tns:stuAge>
  </tns:student>
  <tns:student>
    <tns:stuID>125</tns:stuID>
    <tns:stuName>tns:Pavan</tns:stuName>
    <tns:stuAge>22</tns:stuAge>
  </tns:student>
  <tns:student>
    <tns:stuID>126</tns:stuID>
    <tns:stuName>tns:Abhi</tns:stuName>
    <tns:stuAge>22</tns:stuAge>
  </tns:student>
  <tns:student>
    <tns:stuID>127</tns:stuID>
    <tns:stuName>tns:Puni</tns:stuName>
    <tns:stuAge>22</tns:stuAge>
  </tns:student>
</tns:root>
